image_root: ''
ann_root: '' 

pretrained: 'checkpoint/cp_caption_celeba.pth' 
img_encoder: 'arcface'
batch_size: 32

# generation configs
image_size: 112
max_length: 40  
min_length: 18
num_beams: 3
prompt: 'a photo of a person where '
