image_root: './datasets/face2text/images/'
ann_root: './datasets/face2text/annotation'
dataset: 'face2text'

pretrained: 'output/pretrain/cp_pretrain_flip_02.pth'
img_encoder: 'arcface_50'
batch_size: 128
init_lr: 1e-5 

# generation configs
image_size: 112
max_length: 60  
min_length: 15
num_beams: 5
prompt: 'a photo of a person where '

# optimizer
weight_decay: 0.05
min_lr: 1e-6
max_epoch: 12