image_root: ''
ann_root: '' 

pretrained: 'checkpoint/cp_caption_celeba.pth' 
img_encoder: 'arcface_50'
batch_size: 32

# generation configs
image_size: 112
max_length: 40  
min_length: 15
num_beams: 5
prompt: 'a photo of a person where '
