image_root: ''
ann_root: ''

# set pretrained as a file path or an url
pretrained: 'checkpoint/cp_retrieval_celeba.pth' 

img_encoder: 'arcface'
batch_size_train: 32
batch_size_test: 64
init_lr: 5e-5 #1e-5
negative_all_rank: True

image_size: 112
queue_size: 65536 #57600
alpha: 0.4
k_test: 256