image_root: './datasets/celeba_dialog/images/'
ann_root: './datasets/celeba_dialog/annotation'
dataset: 'celeba_dialog'
pretrained: 'output/pretrain/cp_pretrain_flip_2.pth' # 2(1.18), 4 (.6109)

img_encoder: 'arcface_50'
batch_size_train: 128
batch_size_test: 64
init_lr: 8e-6 #1e-5
max_length: 40

image_size: 112
queue_size: 65536
alpha: 0.4
k_test: 12
negative_all_rank: True

# optimizer
weight_decay: 0.05
min_lr: 1e-6
max_epoch: 25