image_root: './datasets/face2text/images/'
ann_root: './datasets/face2text/annotation'
dataset: 'face2text'
pretrained: 'output/pretrain/cp_pretrain_flip_02.pth' #2(2.239), 3(1.533)

img_encoder: 'arcface_50'
batch_size_train: 128
batch_size_test: 128
init_lr: 1e-5 
max_length: 65

image_size: 112
queue_size: 65536 
alpha: 0.4
k_test: 12  
negative_all_rank: True

# optimizer
weight_decay: 0.05
min_lr: 1e-6
max_epoch: 40 #30